#!/bin/sh
# GPL 3+ - Copyright (C) 2014-2015  pancake, Maijin
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='rabin -k file'
BROKEN=
FILE=../../bins/elf/analysis/hello-linux-x86_64
ARGS=
CMDS='!rabin2 -k ${R2_FILE}'
EXPECT=''
EXPECT_ERR="r_core: Cannot open file
"
run_test

NAME='TODO: test on pie fatmach0'
FILE=../../bins/mach0/fatmach0-3true
BROKEN=1
ARGS=
CMDS='!rabin2 -B 0x2000000 -G 0x1000 -e ${R2_FILE}'
EXPECT='???'
run_test

NAME='rabin2 -qOp/.data/rwx on PE32'
FILE=../../bins/pe/test.exe
ARGS=
CMDS='rm /tmp/rabin2testpe.exe
!rabin2 -qOp/.data/rwx -o/tmp/rabin2testpe.exe ${R2_FILE}
!rabin2 -S /tmp/rabin2testpe.exe
rm /tmp/rabin2testpe.exe
'
EXPECT='wx e0000040 @ 0x244
[Sections]
00 0x00000400 35328 0x00401000 36864 -r-x .text
01 0x00008e00  9216 0x0040a000 12288 -r-- .rdata
02 0x0000b200  4096 0x0040d000 12288 -rwx .data
03 0x0000c200   512 0x00410000  4096 -r-- .rsrc
04 0x0000c400  3584 0x00411000  4096 -r-- .reloc
'
run_test

NAME='rabin2 -qOp//8 on PE32+'
FILE=../../bins/pe/normal64.exe
ARGS=
CMDS='rm /tmp/rabin2testpe.exe
!rabin2 -qOp//8 -o/tmp/rabin2testpe.exe ${R2_FILE}
!rabin2 -S /tmp/rabin2testpe.exe
rm /tmp/rabin2testpe.exe
'
EXPECT='wx 10000000 @ 0x16c
[Sections]
00 0x00000200   512 0x00401000  4096 s--- sect_0
'
run_test
