#!/bin/sh
# LGPL - Copyright (C) 2014-2015 Maijin, pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="axt udis86"
BROKEN=
FILE=../../bins/elf/analysis/main
ARGS=
CMDS='e asm.arch = x86.udis
e anal.arch = x86.udis
e scr.color = false
e scr.wheel = false
aa
axt @ str.Hello_World'
EXPECT='sym.main 0x40050a [data] mov edi, str.Hello_World
'
run_test

NAME="axt udis86: IOLI0"
BROKEN=
FILE=../../bins/elf/ioli/crackme0x00
IGNORE_ERR=1
ARGS=
CMDS='e asm.arch = x86.udis
e anal.arch = x86.udis
e scr.color=false
e scr.wheel = false
aa
axt @ str.Password:'
EXPECT='main 0x804843c [data] mov dword [esp], str.Password:
'
run_test

NAME="axf string ref udis86"
BROKEN=
FILE=../../bins/elf/ioli/crackme0x03
ARGS=
CMDS='e asm.arch = x86.udis
e anal.arch = x86.udis
e scr.color = false
e scr.wheel = false
aa
axt str.Sdvvzrug_RN
axf 0x804848a
'
EXPECT='sym.test 0x804848a [data] mov dword [esp], str.Sdvvzrug_RN
d 0x804848a mov dword [esp], str.Sdvvzrug_RN
'
if [ -n "${TRAVIS}" ]; then
  unset BROKEN
  return
else
  run_test
fi
