#!/bin/sh

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='a8 analyze bytes'
BROKEN=
FILE=-
ARGS=
CMDS='
e asm.arch=x86
e asm.bits=64
e asm.os=linux
a8 0x55|
'
EXPECT='address: 0x0
opcode: push rbp
mnemonic: push
prefix: 0
id: 588
bytes: 55
refptr: 0
size: 1
type: upush
esil: rbp,8,rsp,-=,rsp,=[8]
stack: inc
family: cpu
stackop: inc
stackptr: 8
'
run_test
