#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='ensure jump within a function is added to the basic block'
BROKEN=1
FILE=../../bins/elf/echo
ARGS='-A'
CMDS='s 0xf34
afb.

'
EXPECT='0x00000f34 0x00000f4b 00:0000 23 j 0x00001144
'
run_test
