#!/bin/sh
# GPL 3+ - Copyright (C) 2016 pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="aaa with axt"
FILE=../../bins/anal/keygen.exe
CMDS="aaa
axt 0x4bffb0"
EXPECT="(nofunc) 0x4bfe53 [DATA] mov edx, 0x4bffb0
"
run_test

NAME="aaa with maxbbsz"
FILE=../../bins/anal/flare_notepad.ex
CMDS="e anal.bb.maxsize = 2048
aaa
pdf~ret?"
EXPECT="1
"
run_test

NAME="aaa with avra"
FILE=../../bins/elf/class_test
CMDS="aaa
avra"
EXPECT="VMI Type Info at 0x08048f4c:
  Reference to RTTI's type class: 0x0804b140
  Reference to type's name: 0x08048f6c
  Flags: 0x0
  Count of base classes: 0x2
      Base class type descriptor address: 0x08048f74
      Base class flags: 0x2
      Base class type descriptor address: 0x08048fac
      Base class flags: 0x402

VMI Type Info at 0x08048f4c:
  Reference to RTTI's type class: 0x0804b140
  Reference to type's name: 0x08048f6c
  Flags: 0x0
  Count of base classes: 0x2
      Base class type descriptor address: 0x08048f74
      Base class flags: 0x2
      Base class type descriptor address: 0x08048fac
      Base class flags: 0x402

Type Info at 0x08048f74:
  Reference to RTTI's type class: 0x0804b048
  Reference to type's name: 0x08048f7c

SI Type Info at 0x08048f84:
  Reference to RTTI's type class: 0x0804b114
  Reference to type's name: 0x08048f90
  Reference to parent's type name: 0x08048fac

SI Type Info at 0x08048f98:
  Reference to RTTI's type class: 0x0804b114
  Reference to type's name: 0x08048fa4
  Reference to parent's type name: 0x08048fac

Type Info at 0x08048fac:
  Reference to RTTI's type class: 0x0804b048
  Reference to type's name: 0x08048fb4

"
run_test
