#!/bin/sh
# GPL 3+ - Copyright (C) 2016 pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="aav without vinfun"
FILE=../../bins/elf/analysis/mipsbe-busybox
CMDS="af @ 0x0040dea4
e anal.vinfun=false
aav
pd 1 @ 0x0040decc~?andi
"
EXPECT="1
"
run_test

NAME="aav with vinfun"
FILE=../../bins/elf/analysis/mipsbe-busybox
CMDS="af @ 0x0040dea4
e anal.vinfun=true
aav
pd 1 @ 0x0040decc~?dword
"
EXPECT="1
"
run_test

NAME="aav thumb detection"
FILE=../../bins/firmware/armthumb.bin
ARGS="-aarm -b32"
CMDS="aav
f
"
EXPECT="0x0000000c 4 aav.0x0000000c
"
run_test
