#!/bin/sh
# LGPL - Copyright (C) 2014 Fedor Sakharov
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

mkdir -p /tmp/r2-regressions/

if [ $? -eq 1 ]; then
	echo "Failed to create directory in /tmp/r2-regressions/dwarf"
fi

cp -f ../bins/elf/analysis/dwarftest /tmp/r2-regressions/dwarftest
cp -f ../bins/src/dwarftest.c /tmp/r2-regressions/dwarftest.c

#run_test

NAME="pdf dwarf invalid main for analysis not found (aa)"
BROKEN=
FILE=/tmp/r2-regressions/dwarftest
IGNORE_ERR=1
ARGS=
BROKEN=
CMDS='e asm.dwarf=true
e anal.nopskip=true # if set to true it fucks the test
aa # full analysis fuckups main
pd 1 @main'
EXPECT='/ (fcn) main 44
|   main ();
|           ; var int local_4h @ rbp-0x4
|           ; DATA XREF from 0x0040045d (entry0)
|           0x0040052d      55             push rbp                    ; dwarftest.c:4 {
'
run_test
